version: '2.1'
services:
    kong-database:
        image: postgres:9.6
        container_name: kong-postgres
        restart: 'always'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: kong
            POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
            POSTGRES_DB: kong
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "kong"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            default:
                aliases:
                    - kong-database
    kong-migration:
        image: kong:2.1
        depends_on:
            kong-database:
                condition: service_healthy
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_PG_DATABASE=kong
            - KONG_PG_USER=kong
            - KONG_PG_PASSWORD=${KONG_PG_PASSWORD:-kong}
        command: kong migrations bootstrap
        networks:
            default:
                aliases:
                    - kong-migration
    kong:
        image: kong:2.1
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_PG_USER=kong
            - KONG_PG_DATABASE=kong
            - KONG_PG_PASSWORD=${KONG_PG_PASSWORD:-kong}
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_LISTEN=0.0.0.0:8001
        ports:
            - 80:8000
            - 443:8443
        expose:
            - 8000
            - 8443
            - 8001
            - 8444
        restart: 'always'
        networks:
            default:
                aliases: 
                    - kong
        #logging:
        #    driver: "fluentd"
        #    options:
        #        fluentd-address: $FLUENTD_ADDRESS
        #        tag: docker.nginx.{{.Name}}
    konga:
        image: pantsel/konga
        expose:
            - 1337
        ports:
            - 1337:1337
        volumes:
            - ./konga:/app/kongadata
        environment:
            - NODE_ENV=production
        depends_on:
            - kong
        restart: 'always'
        networks:
            default:
                aliases:
                    - konga
